import { ArrowRight, CalendarCheck2, CarFront, CheckCircle2, CircleParking, Clock3, Cpu, DoorOpen, QrCode, Radar, RotateCw, Wifi } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import Link from "next/link";
import { Container } from "@/components/layout/container";
import { PublicNavbar } from "@/components/layout/public-navbar";
import { Brand } from "@/components/shared/brand";
import { buttonStyles } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { cn } from "@/lib/cn";

const capacity = [
  { label: "Total capacity", value: "4", icon: CircleParking, tone: "bg-slate-100 text-slate-700" },
  { label: "Available", value: "2", icon: CheckCircle2, tone: "bg-emerald-50 text-emerald-700" },
  { label: "Reserved", value: "1", icon: CalendarCheck2, tone: "bg-blue-50 text-blue-700" },
  { label: "Occupied", value: "1", icon: CarFront, tone: "bg-amber-50 text-amber-800" },
];
const steps = [
  ["01", "Check availability", "See parking capacity for your preferred date and time.", Radar],
  ["02", "Reserve parking", "Book one parking space in advance.", CalendarCheck2],
  ["03", "Park automatically", "On arrival, the hardware finds an empty physical parking position.", RotateCw],
  ["04", "Confirm & manage", "After parking, confirm with QR and manage your session online.", QrCode],
] as const;
const features = [
  ["Advance reservations", "Secure parking capacity before you leave.", CalendarCheck2],
  ["Live capacity tracking", "See a clear facility-wide availability summary.", Radar],
  ["Time-based booking", "Choose your date, start time and duration.", Clock3],
  ["QR parking confirmation", "Confirm your session digitally after parking.", QrCode],
  ["Automated hardware", "Let the physical system locate an empty position.", RotateCw],
  ["IoT synchronization", "Keep parking activity connected to the cloud.", Wifi],
] as const;

export default function Home() {
  return <div id="top" className="min-h-screen overflow-x-clip bg-background"><PublicNavbar items={[{ label: "Home", href: "#top", active: true }, { label: "How It Works", href: "#how-it-works" }, { label: "Features", href: "#features" }, { label: "Login", href: "/login" }]} ctaHref="/book" /><main><Hero /><CapacityPreview /><HowItWorks /><ConnectedParking /><Features /><FinalCta /></main><Footer /></div>;
}
function Hero() {
  return <section className="border-b border-slate-200 bg-white" aria-labelledby="hero-title"><Container className="grid items-center gap-12 py-16 sm:py-20 lg:grid-cols-[1fr_0.9fr] lg:py-28"><div className="max-w-2xl"><p className="text-xs font-bold tracking-[0.18em] text-blue-700">CONNECTED PARKING, MADE SIMPLE</p><h1 id="hero-title" className="mt-5 text-4xl font-bold leading-[1.05] tracking-[-0.04em] text-slate-950 sm:text-5xl lg:text-6xl">Smarter Parking, Before You Even Arrive.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Check live parking availability, reserve a space in advance, and manage your parking session through one connected SmartPark experience.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/book" className={buttonStyles({ size: "lg" })}>Book Parking <ArrowRight className="size-4" aria-hidden="true" /></Link><a href="#how-it-works" className={buttonStyles({ variant: "outline", size: "lg" })}>See How It Works</a></div><p className="mt-7 text-sm font-medium text-slate-500">Reserve parking before you arrive, let SmartPark handle the rest.</p></div><Card className="overflow-hidden shadow-2xl shadow-slate-900/10"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">SmartPark Central</p><h2 className="mt-1 text-lg font-bold text-slate-950">Parking availability</h2></div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800"><span className="size-2 rounded-full bg-emerald-500" />Live</span></div><div className="p-5 sm:p-6"><div className="grid grid-cols-4 gap-2" aria-label="Four generic capacity indicators"><Space state="available" /><Space state="available" /><Space state="reserved" /><Space state="occupied" /></div><div className="mt-6 flex items-end justify-between"><div><p className="text-sm text-slate-500">Spaces available now</p><p className="mt-1 text-4xl font-bold text-slate-950">2 <span className="text-base font-medium text-slate-500">of 4</span></p></div><CircleParking className="size-10 text-blue-700" aria-hidden="true" /></div></div></Card></Container></section>;
}
function Space({ state }: { state: "available" | "reserved" | "occupied" }) { const styles={available:"border-emerald-300 bg-emerald-50 text-emerald-800",reserved:"border-blue-300 bg-blue-50 text-blue-800",occupied:"border-amber-300 bg-amber-50 text-amber-900"}; return <div className={cn("flex aspect-[3/4] min-w-0 items-center justify-center rounded-lg border",styles[state])}><CarFront className="size-5 sm:size-7" aria-hidden="true"/><span className="sr-only">{state} capacity unit</span></div>; }
function CapacityPreview() { return <section className="border-b border-slate-200 bg-slate-50" aria-labelledby="capacity-title"><Container className="py-14 sm:py-16"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[0.16em] text-blue-700">LIVE PARKING</p><h2 id="capacity-title" className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Capacity at a glance.</h2></div><p className="max-w-md text-sm leading-6 text-slate-600">A facility-wide view—no physical position selection required.</p></div><div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{capacity.map(item=><Metric key={item.label} {...item}/>)}</div></Container></section>; }
function Metric({label,value,icon:Icon,tone}:{label:string;value:string;icon:LucideIcon;tone:string}) { return <Card className="p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value}</p></div><div className={cn("flex size-10 items-center justify-center rounded-lg",tone)}><Icon className="size-5" aria-hidden="true"/></div></div></Card>; }
function HowItWorks() { return <section id="how-it-works" className="scroll-mt-20 border-b border-slate-200 bg-white py-20 sm:py-24" aria-labelledby="how-title"><Container><Intro eyebrow="ONE CONNECTED JOURNEY" title="How SmartPark works" description="The website reserves capacity. The parking hardware handles the physical movement." id="how-title"/><ol className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map(([n,title,description,Icon])=><li key={n} className="rounded-xl border border-slate-200 p-5"><div className="flex size-11 items-center justify-center rounded-lg bg-blue-50 text-blue-700"><Icon className="size-5" aria-hidden="true"/></div><p className="mt-5 font-mono text-xs font-bold text-blue-700">{n}</p><h3 className="mt-1 font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></li>)}</ol></Container></section>; }
function ConnectedParking() { const flow=[[Radar,"Vehicle detected"],[DoorOpen,"Gate opens"],[RotateCw,"Empty position found"],[QrCode,"Parking confirmed"]] as const; return <section className="border-b border-slate-200 bg-slate-950 py-20 text-white sm:py-24" aria-labelledby="iot-title"><Container><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:items-center"><div><p className="text-xs font-bold tracking-[0.16em] text-blue-300">CONNECTED PHYSICAL PARKING</p><h2 id="iot-title" className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Software convenience. Hardware automation.</h2><p className="mt-4 text-base leading-7 text-slate-300">At the facility, ultrasonic detection and the Arduino-controlled gate begin the physical journey. The rotating platform searches for an empty position; you confirm digitally after parking.</p><div className="mt-6 flex items-center gap-2 text-sm text-slate-300"><Cpu className="size-4 text-blue-300"/>ESP32 cloud connectivity keeps status synchronized.</div></div><div className="grid gap-3 sm:grid-cols-2">{flow.map(([Icon,label],index)=><div key={label} className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/5 p-4"><span className="font-mono text-xs text-blue-300">0{index+1}</span><Icon className="size-5" aria-hidden="true"/><span className="text-sm font-semibold">{label}</span></div>)}</div></div></Container></section>; }
function Features() { return <section id="features" className="scroll-mt-20 bg-slate-50 py-20 sm:py-24" aria-labelledby="features-title"><Container><Intro eyebrow="BUILT FOR CERTAINTY" title="Everything needed for a smoother arrival." description="Focused tools connect advance planning, physical parking and session management." id="features-title"/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([title,description,Icon])=><article key={title} className="rounded-xl border border-slate-200 bg-white p-5"><Icon className="size-5 text-blue-700" aria-hidden="true"/><h3 className="mt-4 font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></Container></section>; }
function FinalCta() { return <section className="bg-slate-50 pb-20 sm:pb-24"><Container><div className="rounded-2xl bg-blue-700 px-6 py-12 text-center text-white sm:px-10 sm:py-16"><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Know your parking before you arrive.</h2><p className="mx-auto mt-4 max-w-xl text-blue-100">Check capacity, reserve ahead and let SmartPark handle the physical parking process.</p><Link href="/book" className={buttonStyles({variant:"outline",size:"lg",className:"mt-8 border-white bg-white text-blue-800 hover:bg-blue-50"})}>Reserve Parking <ArrowRight className="size-4"/></Link></div></Container></section>; }
function Footer() { return <footer className="border-t border-slate-200 bg-white py-8"><Container className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><Brand showTagline/><p className="mt-3 text-xs text-slate-500">© 2026 SmartPark</p></div><p className="text-sm text-slate-500">Smart parking reservation &amp; IoT management</p></Container></footer>; }
function Intro({eyebrow,title,description,id}:{eyebrow:string;title:string;description:string;id:string}) { return <div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold tracking-[0.16em] text-blue-700">{eyebrow}</p><h2 id={id} className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">{title}</h2><p className="mt-4 text-base leading-7 text-slate-600">{description}</p></div>; }
