"use client";
import { CalendarPlus, CarFront, Clock3, History, QrCode, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import QRCode from "react-qr-code";
import { AppShell } from "@/components/layout/app-shell";
import { Container } from "@/components/layout/container";
import { PageHeader } from "@/components/layout/page-header";
import { Button, buttonStyles } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/status-badge";
import { mockUser } from "@/data/mock";
import { useAuth } from "@/features/auth/auth-provider";
import { cancelReservation, checkoutReservation, confirmReservationParking, getMyReservations } from "@/services/reservations";
import type { ApiReservation, SmartParkStatus } from "@/types";

export function BookingsView() {
  const { profile } = useAuth();
  const [items, setItems] = useState<ApiReservation[]>([]), [loading, setLoading] = useState(true), [busyId, setBusyId] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<ApiReservation | null>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  const load = useCallback(async () => setItems(await getMyReservations()), []);
  useEffect(() => { getMyReservations().then(setItems).catch((value) => setError(value instanceof Error ? value.message : "Unable to load bookings.")).finally(() => setLoading(false)); }, []);
  // A booking may be verified by an admin after this page loads, so refresh only while a booked item can still enter the arrival flow.
  const shouldPoll = items.some((item) => item.status === "BOOKED");
  useEffect(() => { if (!shouldPoll) return; const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load().catch(() => undefined); }, 5000); return () => window.clearInterval(timer); }, [load, shouldPoll]);
  const upcoming = items.filter((item) => item.status === "BOOKED"), parked = items.filter((item) => item.status === "PARKED"), history = items.filter((item) => ["COMPLETED", "CANCELLED", "EXPIRED"].includes(item.status));
  async function cancel() { if (!selected) return; setBusyId(selected.id); setError(""); try { await cancelReservation(selected.id); await load(); dialog.current?.close(); setNotice("Reservation cancelled."); } catch (value) { setError(value instanceof Error ? value.message : "Unable to cancel reservation."); } finally { setBusyId(""); } }
  async function checkout(item: ApiReservation) { setBusyId(item.id); setError(""); try { await checkoutReservation(item.id); await load(); setNotice("Parking session completed."); } catch (value) { setError(value instanceof Error ? value.message : "Unable to complete the parking session."); } finally { setBusyId(""); } }
  return <AppShell user={{ ...mockUser, ...profile }}><main className="min-w-0"><Container className="py-8 sm:py-10 lg:py-12"><PageHeader title="My Bookings" description="Follow your reservations from booking through parking history." action={<Link href="/book" className={buttonStyles()}><CalendarPlus className="size-4" />Book Parking</Link>} />{notice && <p role="status" className="mt-6 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}{error && <p role="alert" className="mt-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading ? <Card className="mt-8"><CardContent className="py-14 text-center text-sm text-slate-600">Loading your reservations…</CardContent></Card> : <><Section title="Upcoming" description="Booked parking spaces waiting for your arrival." icon={Clock3}>{upcoming.length ? <div className="grid gap-5 lg:grid-cols-2">{upcoming.map((item) => <Upcoming key={item.id} item={item} onCancel={() => { setSelected(item); dialog.current?.showModal(); }} />)}</div> : <Empty title="No upcoming bookings" text="Reserve a parking space when you need one." action />}</Section><Section title="Parked" description="Active parking sessions confirmed after parking." icon={CarFront}>{parked.length ? <div className="grid gap-5 lg:grid-cols-2">{parked.map((item) => <Parked key={item.id} item={item} busy={busyId === item.id} onCheckout={() => void checkout(item)} />)}</div> : <Empty title="No active parking session" text="A confirmed parking session will appear here." />}</Section><Section title="History" description="Completed, cancelled and expired reservations." icon={History}>{history.length ? <HistoryList items={history} /> : <Empty title="No parking history yet" text="Past reservations will appear here." />}</Section></>}</Container></main><dialog ref={dialog} className="m-auto w-[min(28rem,calc(100%-2rem))] rounded-xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-950/40" aria-labelledby="cancel-title"><div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 id="cancel-title" className="text-lg font-bold">Cancel this reservation?</h2><p className="mt-2 text-sm text-slate-600">The reserved parking capacity will become available again.</p></div><button onClick={() => dialog.current?.close()} aria-label="Close cancellation dialog" className="flex size-10 items-center justify-center rounded-lg hover:bg-slate-100"><X className="size-4" /></button></div><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button variant="outline" onClick={() => dialog.current?.close()} disabled={Boolean(busyId)}>Keep Booking</Button><Button variant="destructive" onClick={() => void cancel()} disabled={Boolean(busyId)}>{busyId ? "Cancelling…" : "Cancel Reservation"}</Button></div></div></dialog></AppShell>;
}

function Section({ title, description, icon: Icon, children }: { title: string; description: string; icon: typeof Clock3; children: React.ReactNode }) { return <section className="mt-8" aria-labelledby={`${title.toLowerCase()}-heading`}><div className="mb-4 flex gap-3"><span className="flex size-10 items-center justify-center rounded-lg bg-blue-50 text-blue-700"><Icon className="size-5" /></span><div><h2 id={`${title.toLowerCase()}-heading`} className="text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-slate-600">{description}</p></div></div>{children}</section>; }
function Upcoming({ item, onCancel }: { item: ApiReservation; onCancel: () => void }) { const [confirming,setConfirming]=useState(false);const [confirmError,setConfirmError]=useState("");async function confirm(){setConfirming(true);setConfirmError("");try{await confirmReservationParking(item.id);window.location.reload()}catch(value){setConfirmError(value instanceof Error?value.message:"Unable to confirm parking.");setConfirming(false)}}return <Card><CardHeader className="flex flex-row items-start justify-between border-b border-slate-200"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Parking reservation</p><CardTitle className="mt-1">{formatDate(item.startAt)}</CardTitle></div><StatusBadge status="reserved" /></CardHeader><CardContent className="p-5 sm:p-6"><Details item={item} />{item.arrivalState === "PARKING_DETECTED" && <div role="status" className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-4"><p className="font-semibold text-emerald-900">Vehicle parking detected</p><p className="mt-1 text-sm text-emerald-800">Confirm your parking using the QR code or the button below.</p></div>}{item.arrivalState === "AWAITING_HARDWARE" && <p role="status" className="mt-5 rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm font-semibold text-blue-800">Arrival verified — waiting for parking hardware.</p>}{confirmError&&<p role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{confirmError}</p>}<div className="mt-6 grid gap-4 border-t border-slate-200 pt-5 sm:grid-cols-[11rem_1fr]"><div role="img" aria-label="QR for post-parking confirmation" className="rounded-lg border border-slate-200 bg-white p-3"><QRCode value={`${process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"}/verify/${item.qrToken}`} className="h-auto w-full" aria-hidden="true" /></div><div><div className="flex items-center gap-2 font-semibold"><QrCode className="size-4 text-blue-700" />Confirm after parking</div><p className="mt-2 text-sm leading-6 text-slate-600">Use this QR after your vehicle is parked to activate your parking session.</p>{item.arrivalState==="PARKING_DETECTED"&&<Button className="mt-4 w-full" disabled={confirming} onClick={()=>void confirm()}>{confirming?"Confirming...":"Confirm Parking"}</Button>}<Button variant="outline" className="mt-4 w-full text-red-700 hover:border-red-200 hover:bg-red-50" onClick={onCancel} disabled={confirming}>Cancel Booking</Button></div></div></CardContent></Card>; }
function Parked({ item, busy, onCheckout }: { item: ApiReservation; busy: boolean; onCheckout: () => void }) { return <Card><CardHeader className="flex flex-row items-start justify-between border-b border-slate-200"><div><p className="text-xs font-bold uppercase tracking-wider text-amber-700">Current parking</p><CardTitle className="mt-1">Active session</CardTitle></div><StatusBadge status="parked" /></CardHeader><CardContent className="p-5 sm:p-6"><Details item={item} /><dl className="mt-5 border-t border-slate-200 pt-5"><Detail label="Parked at" value={item.parkedAt ? formatDateTime(item.parkedAt) : "Confirmed"} /></dl><Button className="mt-6 w-full" disabled={busy} onClick={onCheckout}>{busy ? "Ending Parking…" : "End Parking"}</Button></CardContent></Card>; }
function Details({ item }: { item: ApiReservation }) { return <dl className="grid grid-cols-2 gap-5"><Detail label="Date" value={formatDate(item.startAt)} /><Detail label="Start time" value={formatTime(item.startAt)} /><Detail label="Duration" value={`${item.durationMinutes} minutes`} /><Detail label="Vehicle" value={item.vehicleNumber} /></dl>; }
function HistoryList({ items }: { items: ApiReservation[] }) { return <Card className="overflow-hidden"><div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{formatDate(item.startAt)} · {formatTime(item.startAt)}</p><p className="mt-1 text-sm text-slate-600">{item.vehicleNumber} · {item.durationMinutes} minutes</p>{item.completedAt && <p className="mt-1 text-xs text-slate-500">Completed {formatDateTime(item.completedAt)}</p>}</div><StatusBadge status={item.status.toLowerCase() as SmartParkStatus} /></div>)}</div></Card>; }
function Empty({ title, text, action = false }: { title: string; text: string; action?: boolean }) { return <Card><CardContent className="py-10 text-center"><p className="font-semibold">{title}</p><p className="mx-auto mt-2 max-w-lg text-sm text-slate-600">{text}</p>{action && <Link href="/book" className={buttonStyles({ className: "mt-5" })}>Book Parking</Link>}</CardContent></Card>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", timeZone: "Asia/Kolkata" }).format(new Date(value)); }
function formatTime(value: string) { return new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit", hour12: true, timeZone: "Asia/Kolkata" }).format(new Date(value)); }
function formatDateTime(value: string) { return `${formatDate(value)}, ${formatTime(value)}`; }
